server.port=9960
server.contextPath=/

#server.ssl.key-store=localhost.p12
#server.ssl.key-store-password=password
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=tomcat

security.oauth2.resource.userInfoUri=http://localhost:9900/user
spring.main.banner-mode=off

logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR

server.auth=http://localhost:9900
access.auth=9dfs23vd2

server.notification=http://localhost:9920
access.notification=96GcWB8a

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/job4j_forum
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:./client/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=LEGACYHTML5

spring.resources.static-locations=file:./client/
spring.resources.cache-period=0

forum.subjects.page-size=20
