#Profile develop для разработки и тестирования профиль.
spring.config.activate.on-profile=develop
# Telegram_develop
tg.username=checkdev_develop_bot
tg.token=6922116952:AAFyGK2RkKjulLRcC5IgBMigcZIyv2X_BTI
# URL login page
server.site.url.login=http://localhost:8080/login
