# Local server (mock)
server.port=9920
server.contextPath=/
# Remote service authentication (auth)
server.auth=http://localhost:9900
# Logging
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR
logging.level.ru.checkdev=DEBUG
logging.file.name=logs/notification.log
# Security
security.oauth2.resource.userInfoUri=http://localhost:9900/user
# Datasource
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/cd_notification
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Liquibase
spring.liquibase.change-log=classpath:db/db.changelog-master.xml
# Telegram
tg.username=checkdev_bot
tg.token=6339059467:AAFDt4a4_aBNQe3oMl382J285WDfJWlnkQs
# Other
spring.main.banner-mode=off
access.key=96GcWB8a
server.site.url.login=http://checkdev.ru/login
