#Profile develop для разработки и тестирования профиль.
spring.config.activate.on-profile=default
# Telegram_default
tg.username=Arcady555Bot
tg.token=6638821195:AAFgnjcmOlbLroeTmAHKAjcdPyS5fENQE0s
#URL login page
server.site.url.login=http://checkdev.ru/login