server.port=8080
server.servlet.context-path=
security.oauth2.resource.userInfoUri=http://localhost:9000/user
security.oauth2.tokenUri=http://localhost:9900/oauth/token
spring.main.banner-mode=off
logging.level.root=INFO
logging.level.ru.checkdev=DEBUG