server.port=9001
server.contextPath=/
security.oauth2.resource.userInfoUri=http://localhost:9000/user
spring.main.banner-mode=off
#logging.level.org.springframework=ERROR
#logging.level.org.hibernate=ERROR
#logging.level.org.apache=ERROR

#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/job4j_auth
spring.datasource.url=jdbc:postgresql://192.168.1.74:5432/job4j_images
spring.datasource.username=postgres
spring.datasource.password=Vvy5fWAL
spring.datasource.driver-class-name=org.postgresql.Driver